In [23]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv('startup_funding.csv')

In [25]:
df.head(2)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN

In [26]:
df.columns = df.columns.str.strip().str.replace(r'\s+', ' ', regex=True)

In [27]:
df.drop(columns=['Remarks'], inplace=True)

In [28]:
df['Investors Name'] = df['Investors Name'].fillna('Undisclosed')
df['SubVertical'] = df['SubVertical'].fillna('Unknown')
df['InvestmentnType'] = df['InvestmentnType'].fillna(df['InvestmentnType'].mode()[0])

In [29]:
df['Amount in USD'] = (
    df['Amount in USD']
    .astype(str)
    .str.replace(',', '')
)

In [30]:
df['Amount in USD'] = pd.to_numeric(df['Amount in USD'], errors='coerce')

In [31]:
df = df.dropna(subset=['Amount in USD'])

In [32]:
df['Amount_in_Cr'] = df['Amount in USD'] * 84 / 10000000

In [33]:
df.set_index('Sr No', inplace=True)

In [34]:
df.rename(columns={
    'Date dd/mm/yyyy': 'date',
    'Startup Name': 'startup',
    'Industry Vertical': 'vertical',
    'SubVertical': 'subvertical',
    'City Location': 'city',
    'Investors Name': 'investor',
    'InvestmentnType': 'round',
    'Amount in USD': 'amount'
}, inplace=True)

In [35]:
df.head()

,date,startup,vertical,subvertical,city,investor,round,amount,Amount_in_Cr
Sr No,,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000.0,1680.000000
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394.0,67.606510
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860.0,154.214424
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000.0,25.200000
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000.0,15.120000

In [37]:
df = df.drop(columns=['amount'])

In [38]:
df['date'] = pd.to_datetime(df['date'], errors='coerce', dayfirst=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2065 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          2059 non-null   datetime64[ns]
 1   startup       2065 non-null   object
 2   vertical      1934 non-null   object
 3   subvertical   2065 non-null   object
 4   city          1930 non-null   object
 5   investor      2065 non-null   object
 6   round         2065 non-null   object
 7   Amount_in_Cr  2065 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 145.2+ KB

In [40]:
df.to_csv('startup_cleaned.csv',index=False)

In [41]:
import os
print(os.getcwd())

C:\Users\rajan

In [43]:
df.to_csv("C:/Users/rajan/cleaned_data.csv", index=False)